package weekSix.exceptionHandling;

import java.util.Scanner;

public class MainRunner {
	
	public static void main(String [] args) {
		
		Scanner scn = new Scanner(System.in);
		
		try {
		
		System.out.println("Please enter the first number: ");
		int a = scn.nextInt();
		
		System.out.println("Please enterthe second number: ");
		int b = scn.nextInt();
		
		System.out.println("1. Addition, 2.Division");
		int c = scn.nextInt();
		
		Calculator calc = new Calculator();
		
		if (c == 1) {
			calc.add(a, b);
		}
		
		else if (c == 2) {
			calc.division(a, b);
		}
		
		} catch (Exception e){
			System.out.println("Try again");
		}
		
		System.out.println("End of code!");
		
		
		
		scn.close();
	}

}
